import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { StaffAvatar } from "@/components/staff-avatar";
import { SectionHeader, ui } from "@/components/ui-kit";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { design } from "@/constants/design";
import { useColors } from "@/hooks/use-colors";
import { WalkIn, dateKey, money, useApp } from "@/lib/app-store";

type Range = "Today" | "Week" | "Month" | "All";
function bounds(range: Range) { const now = new Date(); const end = dateKey(now); if (range === "All") return { start: "0000-00-00", end }; const start = new Date(now); start.setDate(start.getDate() - (range === "Today" ? 0 : range === "Week" ? 6 : 30)); return { start: dateKey(start), end }; }
function metrics(rows: WalkIn[]) { const sales = rows.filter((row) => row.sold); const value = sales.reduce((sum, row) => sum + (row.budget ?? 0), 0); return { enquiries: rows.length, attended: rows.length, sales: sales.length, value, conversion: rows.length ? sales.length / rows.length * 100 : 0, lost: rows.length - sales.length, average: sales.length ? value / sales.length : 0 }; }
function inRange(date: string, range: Range) { const value = bounds(range); return date >= value.start && date <= value.end; }

export default function EmployeeProfileScreen() {
  const colors = useColors();
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { staff, walkIns } = useApp();
  const person = staff.find((item) => item.id === id);
  const [range, setRange] = useState<Range>("Month");
  const [category, setCategory] = useState("All");
  const rows = useMemo(() => walkIns.filter((row) => row.staffId === id && inRange(row.date, range) && (category === "All" || row.category === category)), [walkIns, id, range, category]);
  const data = metrics(rows);
  const days = useMemo(() => [...new Set(rows.map((row) => row.date))].sort().slice(-10).map((date) => ({ date, ...metrics(rows.filter((row) => row.date === date)) })), [rows]);
  const max = Math.max(...days.map((day) => day.enquiries), 1);
  if (!person) return <ScreenContainer><View style={{ padding: 20 }}><Text style={{ color: colors.foreground, fontSize: 20, fontWeight: "900" }}>Employee not found</Text><Pressable onPress={() => router.back()}><Text style={{ color: colors.primary, marginTop: 10 }}>Go back</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer containerClassName="bg-background"><Stack.Screen options={{ title: person.name }} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Pressable onPress={() => router.back()} style={ui.row}><IconSymbol name="chevron.left" size={19} color={colors.muted} /><Text style={{ color: colors.muted, fontSize: 12, fontWeight: "800" }}>Team</Text></Pressable>
    <View style={[styles.profileHero, { backgroundColor: colors.foreground }]}><View style={styles.profileGlow} /><StaffAvatar staff={person} size={104} /><View style={{ flex: 1, marginLeft: 16 }}><Text style={styles.profileEyebrow}>EMPLOYEE PROFILE</Text><Text style={styles.profileName}>{person.name}</Text><Text style={styles.profileRole}>{person.jobTitle ?? person.role}</Text><View style={[ui.row, { gap: 6, marginTop: 11 }]}><View style={[styles.statusDot, { backgroundColor: person.active ? design.colors.green : colors.muted }]} /><Text style={{ color: person.active ? design.colors.green : "#FFFFFF9A", fontSize: 10, fontWeight: "900" }}>{person.status ?? (person.active ? "ACTIVE" : "INACTIVE")}</Text></View></View></View>
    <View style={styles.filterRow}>{(["Today", "Week", "Month", "All"] as Range[]).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.filter, { backgroundColor: range === item ? colors.foreground : colors.surface, borderColor: range === item ? colors.foreground : colors.border }]}><Text style={{ color: range === item ? colors.background : colors.foreground, fontSize: 11, fontWeight: "800" }}>{item}</Text></Pressable>)}</View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{["All", "Road", "MTB", "Gravel", "Hybrid", "Kids", "Service", "Tyres", "Other"].map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, { backgroundColor: category === item ? `${colors.primary}18` : colors.surface, borderColor: category === item ? colors.primary : colors.border }]}><Text style={{ color: category === item ? colors.primary : colors.muted, fontSize: 10, fontWeight: "800" }}>{item}</Text></Pressable>)}</ScrollView>
    <Text style={[styles.kicker, { color: colors.muted }]}>PERFORMANCE OVERVIEW</Text><View style={styles.kpiGrid}><Kpi label="Total enquiries" value={String(data.enquiries)} color={colors.foreground} bg={colors.surface} /><Kpi label="Attended" value={String(data.attended)} color="#FFFFFF" bg={design.colors.blue} /><Kpi label="Sales" value={String(data.sales)} color="#FFFFFF" bg={design.colors.purple} /><Kpi label="Sales value" value={money(data.value)} color="#FFFFFF" bg={design.colors.pink} /><Kpi label="Conversion rate" value={`${data.conversion.toFixed(1)}%`} color="#FFFFFF" bg={design.colors.green} /><Kpi label="Lost opportunities" value={String(data.lost)} color={colors.foreground} bg={colors.surface} /><Kpi label="Average sale value" value={money(data.average)} color="#FFFFFF" bg={design.colors.cyan} /></View>
    <SectionHeader title="Performance over time" action={`${days.length} recorded days`} /><View style={[styles.chartCard, { backgroundColor: colors.surface, borderColor: colors.border }]}>{days.length ? <View style={styles.chart}>{days.map((day) => <View key={day.date} style={styles.chartCol}><View style={styles.track}><View style={[styles.bar, { height: Math.max(7, day.enquiries / max * 110), backgroundColor: day.sales ? design.colors.purple : `${design.colors.blue}55` }]} /></View><Text style={{ color: colors.muted, fontSize: 9 }}>{day.date.slice(8)}</Text></View>)}</View> : <Text style={{ color: colors.muted, fontSize: 12 }}>No recorded activity for this filter.</Text>}<View style={styles.legend}><Text style={{ color: colors.muted, fontSize: 10 }}>Enquiries over time</Text><Text style={{ color: design.colors.purple, fontSize: 10, fontWeight: "900" }}>{data.sales} sales</Text></View></View>
    <SectionHeader title="Profile details" /><View style={[styles.details, { backgroundColor: colors.surface, borderColor: colors.border }]}><Detail label="Employee ID" value={person.employeeId ?? "Not provided"} /><Detail label="Phone" value={person.phone ?? "Not provided"} /><Detail label="Email" value={person.email ?? "Not provided"} /><Detail label="Joining date" value={person.joinedAt} /></View>
    <Text style={{ color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 20 }}>Every figure is calculated from recorded interactions attributed to {person.name}. No unsupported performance information is added.</Text>
  </ScrollView></ScreenContainer>;
}
function Kpi({ label, value, color, bg }: { label: string; value: string; color: string; bg: string }) { return <View style={[styles.kpi, { backgroundColor: bg, borderColor: bg }]}><Text style={{ color: color === "#FFFFFF" ? "#FFFFFFB8" : "#7D8798", fontSize: 9, fontWeight: "900", textTransform: "uppercase" }}>{label}</Text><Text style={{ color, fontSize: 21, fontWeight: "900", marginTop: 14 }}>{value}</Text></View>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={{ color: "#7D8798", fontSize: 10, fontWeight: "800" }}>{label}</Text><Text style={{ color: "#111A2E", fontSize: 13, fontWeight: "800", marginTop: 4 }}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 36 }, profileHero: { minHeight: 168, borderRadius: 23, padding: 18, flexDirection: "row", alignItems: "center", marginTop: 17, overflow: "hidden" }, profileGlow: { position: "absolute", width: 190, height: 190, borderRadius: 95, backgroundColor: `${design.colors.blue}55`, right: -50, top: -70 }, profileEyebrow: { color: "#FFFFFF9A", fontSize: 9, letterSpacing: 1.2, fontWeight: "900" }, profileName: { color: "#FFFFFF", fontSize: 24, fontWeight: "900", marginTop: 7 }, profileRole: { color: "#FFFFFFB8", fontSize: 12, marginTop: 4 }, statusDot: { width: 6, height: 6, borderRadius: 3 }, filterRow: { flexDirection: "row", gap: 7, paddingVertical: 15 }, filter: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9 }, chips: { gap: 7 }, chip: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 }, kicker: { fontSize: 10, fontWeight: "900", letterSpacing: 1.2, marginTop: 20, marginBottom: 10 }, kpiGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, kpi: { width: "31.8%", flexGrow: 1, minHeight: 97, borderRadius: 17, borderWidth: 1, padding: 13, shadowColor: "#93A5BA", shadowOpacity: 0.1, shadowRadius: 12, shadowOffset: { width: 0, height: 5 } }, chartCard: { borderWidth: 1, borderRadius: 20, padding: 16 }, chart: { height: 150, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-around", gap: 4 }, chartCol: { flex: 1, height: 140, alignItems: "center", justifyContent: "flex-end" }, track: { width: "62%", height: 115, justifyContent: "flex-end", borderRadius: 6, backgroundColor: "#F1F4F8", overflow: "hidden" }, bar: { width: "100%", borderRadius: 6 }, legend: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: "#E8EDF3", paddingTop: 11, marginTop: 10 }, details: { borderWidth: 1, borderRadius: 18, padding: 15 }, detail: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#EDF0F5" },
});
