import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Stack, useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { StaffAvatar } from "@/components/staff-avatar";
import { Pill, SectionHeader, ui } from "@/components/ui-kit";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { design } from "@/constants/design";
import { useColors } from "@/hooks/use-colors";
import { CATEGORIES, WalkIn, money, useApp } from "@/lib/app-store";

type Window = "All time" | "This month";
function stats(rows: WalkIn[]) { const sales = rows.filter((row) => row.sold); const value = sales.reduce((sum, row) => sum + (row.budget ?? 0), 0); return { enquiries: rows.length, attended: rows.length, sales: sales.length, value, conversion: rows.length ? sales.length / rows.length * 100 : 0, lost: rows.length - sales.length, lostRate: rows.length ? (rows.length - sales.length) / rows.length * 100 : 0, average: sales.length ? value / sales.length : 0 }; }
function hour(row: WalkIn) { return Number(row.time.slice(0, 2)); }
function day(row: WalkIn) { return new Date(`${row.date}T12:00:00`).toLocaleDateString("en-GB", { weekday: "short" }); }
function bucket(value: number) { return value < 12 ? "Morning" : value < 17 ? "Afternoon" : "Evening"; }
function ratio(value: number, total: number) { return total ? `${Math.round(value / total * 100)}%` : "0%"; }

export default function PerformanceAnalysisScreen() {
  const colors = useColors();
  const router = useRouter();
  const { walkIns, staff } = useApp();
  const [window, setWindow] = useState<Window>("This month");
  const [selectedReason, setSelectedReason] = useState<string>();
  const rows = useMemo(() => { if (window === "All time") return walkIns; const now = new Date(); const start = new Date(now); start.setDate(start.getDate() - 30); const startKey = start.toISOString().slice(0, 10); return walkIns.filter((row) => row.date >= startKey); }, [walkIns, window]);
  const current = stats(rows);
  const lost = rows.filter((row) => !row.sold);
  const lossReasons = useMemo(() => Object.entries(lost.reduce<Record<string, WalkIn[]>>((acc, row) => { const label = row.lostReason ?? "Not specified"; (acc[label] ??= []).push(row); return acc; }, {})).map(([label, items]) => ({ label, items, count: items.length, percentage: lost.length ? items.length / lost.length * 100 : 0 })).sort((a, b) => b.count - a.count), [lost]);
  const selectedLost = lossReasons.find((item) => item.label === selectedReason);
  const funnel = [{ label: "Enquiries", value: current.enquiries, color: design.colors.blue }, { label: "Attended", value: current.attended, color: design.colors.cyan }, { label: "Sales", value: current.sales, color: design.colors.purple }];
  const periods = useMemo(() => { const map = new Map<string, WalkIn[]>(); rows.forEach((row) => { const label = bucket(hour(row)); map.set(label, [...(map.get(label) ?? []), row]); }); return ["Morning", "Afternoon", "Evening"].map((label) => ({ label, rows: map.get(label) ?? [], ...stats(map.get(label) ?? []) })); }, [rows]);
  const days = useMemo(() => { const labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]; return labels.map((label) => { const dayRows = rows.filter((row) => day(row) === label); return { label, rows: dayRows, ...stats(dayRows) }; }); }, [rows]);
  const categories = useMemo(() => CATEGORIES.map((label) => { const categoryRows = rows.filter((row) => row.category === label); return { label, rows: categoryRows, ...stats(categoryRows) }; }).filter((item) => item.enquiries > 0), [rows]);
  const employees = useMemo(() => staff.map((person) => { const employeeRows = rows.filter((row) => row.staffId === person.id); const byCategory = CATEGORIES.map((label) => ({ label, ...stats(employeeRows.filter((row) => row.category === label)) })).filter((item) => item.enquiries > 0).sort((a, b) => b.conversion - a.conversion)[0]; const byDay = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((label) => ({ label, ...stats(employeeRows.filter((row) => day(row) === label)) })).filter((item) => item.enquiries > 0).sort((a, b) => b.conversion - a.conversion)[0]; const byHour = Array.from({ length: 12 }, (_, index) => index + 9).map((hourValue) => ({ hourValue, ...stats(employeeRows.filter((row) => hour(row) === hourValue)) })).filter((item) => item.enquiries > 0).sort((a, b) => b.conversion - a.conversion)[0]; const reason = Object.entries(employeeRows.filter((row) => !row.sold).reduce<Record<string, number>>((acc, row) => { const label = row.lostReason ?? "Not specified"; acc[label] = (acc[label] ?? 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1])[0]; return { person, ...stats(employeeRows), strongestCategory: byCategory, bestDay: byDay, bestHour: byHour, reason }; }), [staff, rows]);
  const bestPeriod = [...periods].filter((item) => item.enquiries > 0).sort((a, b) => b.conversion - a.conversion)[0];
  const weakPeriod = [...periods].filter((item) => item.enquiries > 0).sort((a, b) => a.conversion - b.conversion)[0];
  const bestDay = [...days].filter((item) => item.enquiries > 0).sort((a, b) => b.conversion - a.conversion)[0];
  const weakCategory = [...categories].filter((item) => item.enquiries >= 2).sort((a, b) => a.conversion - b.conversion)[0];
  const strongCategory = [...categories].filter((item) => item.enquiries >= 2).sort((a, b) => b.conversion - a.conversion)[0];
  return <ScreenContainer containerClassName="bg-background"><Stack.Screen options={{ title: "Performance Analysis" }} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Pressable onPress={() => router.back()} style={ui.row}><IconSymbol name="chevron.left" size={19} color={colors.muted} /><Text style={{ color: colors.muted, fontSize: 12, fontWeight: "800" }}>Back</Text></Pressable><View style={ui.between}><View><Text style={[ui.eyebrow, { color: colors.primary, marginTop: 17 }]}>CYCLEINTEL · EVIDENCE LAYER</Text><Text style={[ui.title, { color: colors.foreground, marginTop: 5 }]}>Performance analysis</Text><Text style={[ui.subtitle, { color: colors.muted, marginTop: 4 }]}>Understand where and why opportunities are being lost.</Text></View><View style={[styles.signal, { backgroundColor: `${design.colors.purple}16` }]}><IconSymbol name="chart.pie.fill" size={22} color={design.colors.purple} /></View></View>
    <View style={styles.windowRow}>{(["This month", "All time"] as Window[]).map((item) => <Pressable key={item} onPress={() => setWindow(item)} style={[styles.window, { backgroundColor: window === item ? colors.foreground : colors.surface, borderColor: window === item ? colors.foreground : colors.border }]}><Text style={{ color: window === item ? colors.background : colors.foreground, fontSize: 11, fontWeight: "800" }}>{item}</Text></Pressable>)}</View>
    <View style={[styles.summary, { backgroundColor: "#EEF5FF", borderColor: `${design.colors.blue}32` }]}><Text style={[styles.summaryKicker, { color: design.colors.blue }]}>WHAT THE DATA SAYS</Text><Text style={[styles.summaryTitle, { color: colors.foreground }]}>{current.lost} lost opportunities from {current.enquiries} recorded enquiries</Text><Text style={[styles.summaryCopy, { color: colors.muted }]}>{current.sales} sales · {current.conversion.toFixed(1)}% conversion · {money(current.value)} recorded value</Text></View>
    <SectionHeader title="Lost sales analysis" action="Tap a reason" /><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{lossReasons.length ? lossReasons.map((item, index) => <Pressable key={item.label} onPress={() => setSelectedReason(selectedReason === item.label ? undefined : item.label)} style={[styles.reasonRow, { borderBottomColor: colors.border, backgroundColor: selectedReason === item.label ? `${colors.primary}0D` : "transparent" }]}><View style={[styles.reasonRank, { backgroundColor: index === 0 ? design.colors.pink : `${colors.primary}16` }]}><Text style={{ color: index === 0 ? "#FFFFFF" : colors.primary, fontSize: 10, fontWeight: "900" }}>{item.count}</Text></View><View style={{ flex: 1, marginLeft: 10 }}><View style={ui.between}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "900" }}>{item.label}</Text><Text style={{ color: colors.muted, fontSize: 10 }}>{item.percentage.toFixed(0)}%</Text></View><View style={[styles.track, { backgroundColor: colors.background }]}><View style={[styles.fill, { width: `${Math.max(5, item.percentage)}%`, backgroundColor: index === 0 ? design.colors.pink : colors.primary }]} /></View></View><IconSymbol name={selectedReason === item.label ? "chevron.left" : "chevron.right"} size={16} color={colors.muted} /></Pressable>) : <Empty text="No lost opportunities recorded for this period." />}{selectedLost && <View style={[styles.related, { backgroundColor: colors.background, borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontSize: 11, fontWeight: "900" }}>Related enquiries · {selectedLost.label}</Text>{selectedLost.items.map((row) => <View key={row.id} style={styles.relatedRow}><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 11, fontWeight: "800" }}>{row.category} · {row.requirement}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 2 }}>{row.date} · {row.time} · {staff.find((person) => person.id === row.staffId)?.name ?? "Unknown employee"}</Text></View><Pill color={colors.warning} background={`${colors.warning}16`}>{row.intent}</Pill></View>)}</View>}</View>
    <SectionHeader title="Conversion analysis" action="Enquiries → attendance → sales" /><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.funnel}>{funnel.map((item, index) => <View key={item.label} style={styles.funnelRow}><View style={[styles.funnelLabel, { backgroundColor: `${item.color}16` }]}><Text style={{ color: item.color, fontSize: 11, fontWeight: "900" }}>{item.label}</Text></View><View style={[styles.funnelTrack, { backgroundColor: colors.background }]}><View style={[styles.funnelFill, { width: `${current.enquiries ? Math.max(4, item.value / current.enquiries * 100) : 0}%`, backgroundColor: item.color }]} /></View><Text style={{ color: colors.foreground, fontSize: 14, fontWeight: "900", width: 36, textAlign: "right" }}>{item.value}</Text><Text style={{ color: colors.muted, fontSize: 9, width: 42, textAlign: "right" }}>{ratio(item.value, current.enquiries)}</Text></View>)}</View><Text style={{ color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 12 }}>Attendance equals recorded walk-ins in the current data model. The measurable drop-off is therefore from attended enquiries to completed sales: {current.attended - current.sales} opportunities.</Text></View>
    <SectionHeader title="Time analysis" action="Hour · period · day" /><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={styles.cardKicker}>DAY PART</Text>{periods.map((item) => <BarRow key={item.label} label={item.label} detail={`${item.enquiries} enquiries · ${item.sales} sales`} value={`${item.conversion.toFixed(0)}%`} percent={item.conversion} color={item.label === bestPeriod?.label ? design.colors.green : item.label === weakPeriod?.label ? design.colors.pink : colors.primary} />)}<Text style={[styles.cardKicker, { marginTop: 16 }]}>DAY OF WEEK</Text>{days.map((item) => <BarRow key={item.label} label={item.label} detail={`${item.enquiries} enquiries · ${item.sales} sales`} value={`${item.conversion.toFixed(0)}%`} percent={item.conversion} color={item.label === bestDay?.label ? design.colors.green : colors.primary} />)}</View>
    <SectionHeader title="Category analysis" action="All recorded categories" /><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{categories.map((item, index) => <View key={item.label} style={[styles.categoryRow, { borderBottomColor: colors.border }]}><View style={[styles.categoryDot, { backgroundColor: [design.colors.blue, design.colors.purple, design.colors.pink, design.colors.green][index % 4] }]} /><View style={{ flex: 1 }}><View style={ui.between}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "900" }}>{item.label}</Text><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "900" }}>{item.conversion.toFixed(0)}%</Text></View><Text style={{ color: colors.muted, fontSize: 10, marginTop: 3 }}>{item.enquiries} enquiries · {item.attended} attended · {item.sales} sales · {money(item.value)}</Text></View></View>)}</View>
    <SectionHeader title="Employee analysis" action="Evidence by person" /><View style={{ gap: 9 }}>{employees.filter((item) => item.enquiries > 0).map((item) => <View key={item.person.id} style={[styles.employeeCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={ui.row}><StaffAvatar staff={item.person} size={44} /><View style={{ flex: 1, marginLeft: 10 }}><Text style={{ color: colors.foreground, fontSize: 13, fontWeight: "900" }}>{item.person.name}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 3 }}>{item.enquiries} enquiries · {item.sales} sales · {item.conversion.toFixed(0)}% conversion</Text></View><Text style={{ color: design.colors.purple, fontSize: 16, fontWeight: "900" }}>{money(item.average)}</Text></View><View style={styles.employeeGrid}><InsightCell label="Strongest category" value={item.strongestCategory?.label ?? "Not enough data"} /><InsightCell label="Best day" value={item.bestDay?.label ?? "Not enough data"} /><InsightCell label="Best time" value={item.bestHour ? `${item.bestHour.hourValue}:00` : "Not enough data"} /><InsightCell label="Lost rate" value={`${item.lostRate.toFixed(0)}%`} /><InsightCell label="Common lost reason" value={item.reason?.[0] ?? "Not enough data"} /><InsightCell label="Trend" value={item.sales > 0 ? "Sales recorded" : "Needs more data"} /></View></View>)}</View>
    <SectionHeader title="What should I improve?" action="Calculated actions" /><View style={{ gap: 9 }}>{weakCategory && strongCategory && <Action title={`${weakCategory.label} converts below ${strongCategory.label}`} detail={`${weakCategory.conversion.toFixed(0)}% vs ${strongCategory.conversion.toFixed(0)}% conversion · ${weakCategory.enquiries} vs ${strongCategory.enquiries} enquiries`} color={design.colors.pink} />}{weakPeriod && bestPeriod && <Action title={`${weakPeriod.label} is the weakest day part`} detail={`${weakPeriod.conversion.toFixed(0)}% conversion from ${weakPeriod.enquiries} enquiries vs ${bestPeriod.conversion.toFixed(0)}% in ${bestPeriod.label}`} color={design.colors.amber} />}{lossReasons[0] && <Action title={`Investigate “${lossReasons[0].label}” objections`} detail={`${lossReasons[0].count} lost opportunities · ${lossReasons[0].percentage.toFixed(0)}% of all recorded losses`} color={design.colors.purple} />}{!weakCategory && !weakPeriod && !lossReasons.length && <Empty text="Record more interactions to generate evidence-backed improvement actions." />}</View>
    <Text style={{ color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 22 }}>These are calculated signals, not AI-generated claims. Every action above is supported by the recorded enquiries, outcomes, dates, times, categories, employees, and lost-sale reasons in this workspace.</Text>
  </ScrollView></ScreenContainer>;
}
function BarRow({ label, detail, value, percent, color }: { label: string; detail: string; value: string; percent: number; color: string }) { const colors = useColors(); return <View style={styles.barRow}><View style={{ width: 72 }}><Text style={{ color: colors.foreground, fontSize: 11, fontWeight: "900" }}>{label}</Text><Text style={{ color: colors.muted, fontSize: 8, marginTop: 2 }}>{detail}</Text></View><View style={[styles.track, { flex: 1, backgroundColor: colors.background }]}><View style={[styles.fill, { width: `${Math.max(percent ? 4 : 0, Math.min(percent, 100))}%`, backgroundColor: color }]} /></View><Text style={{ color, fontSize: 11, fontWeight: "900", width: 38, textAlign: "right" }}>{value}</Text></View>; }
function InsightCell({ label, value }: { label: string; value: string }) { return <View style={styles.insightCell}><Text style={{ color: "#7D8798", fontSize: 8, fontWeight: "800" }}>{label}</Text><Text numberOfLines={1} style={{ color: "#111A2E", fontSize: 10, fontWeight: "900", marginTop: 3 }}>{value}</Text></View>; }
function Action({ title, detail, color }: { title: string; detail: string; color: string }) { return <View style={[styles.action, { backgroundColor: `${color}10`, borderColor: `${color}32` }]}><View style={[styles.actionIcon, { backgroundColor: color }]}><IconSymbol name="arrow.up.right" size={15} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={{ color: "#111A2E", fontSize: 12, fontWeight: "900" }}>{title}</Text><Text style={{ color: "#7D8798", fontSize: 10, lineHeight: 14, marginTop: 4 }}>{detail}</Text></View></View>; }
function Empty({ text }: { text: string }) { return <Text style={{ color: "#7D8798", fontSize: 11, paddingVertical: 14 }}>{text}</Text>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 36, maxWidth: 1180, width: "100%", alignSelf: "center" }, signal: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, windowRow: { flexDirection: "row", gap: 7, paddingVertical: 16 }, window: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9 }, summary: { borderRadius: 20, borderWidth: 1, padding: 17, marginBottom: 8, shadowColor: "#A9B8CC", shadowOpacity: 0.1, shadowRadius: 18, shadowOffset: { width: 0, height: 7 } }, summaryKicker: { fontSize: 9, fontWeight: "900", letterSpacing: 1.1 }, summaryTitle: { fontSize: 20, lineHeight: 25, fontWeight: "900", marginTop: 9 }, summaryCopy: { fontSize: 11, marginTop: 7 }, card: { borderWidth: 1, borderRadius: 20, padding: 15 }, reasonRow: { minHeight: 55, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, paddingVertical: 8 }, reasonRank: { width: 32, height: 32, borderRadius: 11, alignItems: "center", justifyContent: "center" }, track: { height: 7, borderRadius: 5, overflow: "hidden", marginTop: 7 }, fill: { height: "100%", borderRadius: 5 }, related: { borderWidth: 1, borderRadius: 14, padding: 11, marginTop: 10 }, relatedRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: "#E8EDF3" }, funnel: { gap: 12 }, funnelRow: { flexDirection: "row", alignItems: "center", gap: 8 }, funnelLabel: { width: 82, paddingVertical: 8, paddingHorizontal: 8, borderRadius: 9 }, funnelTrack: { flex: 1, height: 10, borderRadius: 6, overflow: "hidden" }, funnelFill: { height: "100%", borderRadius: 6 }, cardKicker: { color: "#7D8798", fontSize: 9, fontWeight: "900", letterSpacing: 1.1, marginBottom: 8 }, barRow: { flexDirection: "row", alignItems: "center", gap: 9, paddingVertical: 6 }, categoryRow: { flexDirection: "row", alignItems: "center", gap: 9, borderBottomWidth: 1, paddingVertical: 10 }, categoryDot: { width: 9, height: 9, borderRadius: 4 }, employeeCard: { borderWidth: 1, borderRadius: 18, padding: 14 }, employeeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderTopColor: "#EDF0F5" }, insightCell: { width: "31.8%", minHeight: 38 }, action: { borderWidth: 1, borderRadius: 17, padding: 13, flexDirection: "row", gap: 10 }, actionIcon: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center" },
});
