import { ReactNode } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { design } from "@/constants/design";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";

const DOTS: Record<string, string[]> = { "0": ["111", "101", "101", "101", "111"], "1": ["010", "110", "010", "010", "111"], "2": ["110", "001", "010", "100", "111"], "3": ["110", "001", "010", "001", "110"], "4": ["101", "101", "111", "001", "001"], "5": ["111", "100", "110", "001", "110"], "6": ["011", "100", "111", "101", "111"], "7": ["111", "001", "010", "010", "010"], "8": ["111", "101", "111", "101", "111"], "9": ["111", "101", "111", "001", "110"], ".": ["0", "0", "0", "0", "1"], "%": ["1001", "0010", "0100", "1001", "0010"], "—": ["111", "000", "000", "000", "111"] };

export const ui = StyleSheet.create({
  screen: { paddingHorizontal: design.spacing.lg, paddingTop: design.spacing.lg, paddingBottom: design.spacing.xxl },
  row: { flexDirection: "row", alignItems: "center" },
  between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  eyebrow: { fontSize: design.typography.eyebrow, letterSpacing: design.typography.tracking, textTransform: "uppercase", fontWeight: "800" },
  title: { fontSize: design.typography.display, lineHeight: 36, fontWeight: "800", letterSpacing: -0.8 },
  subtitle: { fontSize: design.typography.body, lineHeight: 20 },
  card: { borderRadius: design.radius.lg, padding: design.spacing.lg, borderWidth: 1, shadowColor: design.shadow.color, shadowOpacity: design.shadow.opacity, shadowRadius: design.shadow.radius, shadowOffset: { width: 0, height: design.shadow.y } },
  sectionTitle: { fontSize: 16, fontWeight: "800", letterSpacing: -0.2 },
  small: { fontSize: design.typography.caption, lineHeight: 15 },
});

export function DotNumber({ value, color = design.colors.ink, size = 3 }: { value: string; color?: string; size?: number }) { return <View style={styles.dotNumber}>{value.split("").map((char, charIndex) => <View key={`${char}-${charIndex}`} style={styles.dotGlyph}>{(DOTS[char] ?? DOTS["—"]).map((row, rowIndex) => <View key={rowIndex} style={styles.dotRow}>{row.split("").map((bit, bitIndex) => <View key={bitIndex} style={[styles.dot, { width: size, height: size, borderRadius: size, backgroundColor: bit === "1" ? color : "transparent" }]} />)}</View>)}</View>)}</View>; }

export function SectionHeader({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { const colors = useColors(); return <View style={[ui.between, { marginTop: 26, marginBottom: 12 }]}><Text style={[ui.sectionTitle, { color: colors.foreground }]}>{title}</Text>{action && (onAction ? <Pressable onPress={onAction} style={({ pressed }) => [styles.action, pressed && { opacity: 0.55 }]}><Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>{action}</Text><IconSymbol name="chevron.right" size={16} color={colors.primary} /></Pressable> : <Text style={{ color: colors.primary, fontSize: 12, fontWeight: "800" }}>{action}</Text>)}</View>; }

export function GlassCard({ children, style, onPress }: { children: ReactNode; style?: object; onPress?: () => void }) { const colors = useColors(); const content = <View style={[ui.card, { backgroundColor: `${colors.surface}F2`, borderColor: colors.border }, style]}>{children}</View>; return onPress ? <Pressable onPress={onPress} style={({ pressed }) => [pressed && { opacity: 0.72, transform: [{ scale: 0.99 }] }]}>{content}</Pressable> : content; }

export function MetricCard({ label, value, detail, icon, accent = "primary", onPress }: { label: string; value: string; detail?: string; icon: string; accent?: "primary" | "success" | "warning"; onPress?: () => void }) { const colors = useColors(); const map: Record<string, { bg: string; fg: string }> = { "Walk-ins": { bg: "#FFFFFF", fg: colors.foreground }, Sales: { bg: design.colors.purple, fg: "#FFFFFF" }, Conversion: { bg: design.colors.blue, fg: "#FFFFFF" }, Lost: { bg: design.colors.pink, fg: "#FFFFFF" }, "Follow-ups": { bg: design.colors.green, fg: "#FFFFFF" } }; const tile = map[label] ?? { bg: colors.surface, fg: colors.foreground }; const accentColor = accent === "success" ? colors.success : accent === "warning" ? colors.warning : colors.primary; const content = <View style={[ui.card, styles.metric, { backgroundColor: tile.bg, borderColor: tile.bg }]}><View style={[ui.between, { marginBottom: 10 }]}><Text style={[ui.eyebrow, { color: tile.fg === "#FFFFFF" ? "#FFFFFFB8" : colors.muted }]}>{label}</Text><View style={[styles.iconCircle, { backgroundColor: tile.fg === "#FFFFFF" ? "#FFFFFF25" : `${accentColor}18` }]}><IconSymbol name={icon} size={17} color={tile.fg === "#FFFFFF" ? "#FFFFFF" : accentColor} /></View></View><DotNumber value={value} color={tile.fg} size={3} /><Text style={[ui.small, { color: tile.fg === "#FFFFFF" ? "#FFFFFFB8" : colors.muted, marginTop: 7 }]}>{detail}</Text></View>; return onPress ? <Pressable onPress={onPress} style={({ pressed }) => [pressed && { opacity: 0.72 }]}>{content}</Pressable> : content; }

export function Pill({ children, color, background }: { children: ReactNode; color?: string; background?: string }) { const colors = useColors(); return <View style={[styles.pill, { backgroundColor: background ?? `${colors.primary}14` }]}><Text style={{ color: color ?? colors.primary, fontSize: 11, fontWeight: "800" }}>{children}</Text></View>; }

export function BarList({ rows, max, color }: { rows: { label: string; value: number; meta?: string }[]; max?: number; color?: string }) { const colors = useColors(); const maxValue = max ?? Math.max(...rows.map((row) => row.value), 1); return <View style={{ gap: 13 }}>{rows.map((row) => <View key={row.label}><View style={ui.between}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "700", flex: 1 }}>{row.label}</Text><Text style={{ color: colors.muted, fontSize: 11, fontWeight: "700" }}>{row.meta ?? row.value}</Text></View><View style={[styles.track, { backgroundColor: colors.background }]}><View style={[styles.fill, { width: `${Math.max(4, row.value / maxValue * 100)}%`, backgroundColor: color ?? colors.primary }]} /></View></View>)}</View>; }

export function EmptyState({ title, description }: { title: string; description: string }) { const colors = useColors(); return <GlassCard style={{ alignItems: "center", paddingVertical: 28 }}><IconSymbol name="chart.bar.fill" size={28} color={colors.muted} /><Text style={{ color: colors.foreground, fontWeight: "800", marginTop: 10 }}>{title}</Text><Text style={{ color: colors.muted, textAlign: "center", fontSize: 12, lineHeight: 18, marginTop: 5 }}>{description}</Text></GlassCard>; }

const styles = StyleSheet.create({ action: { flexDirection: "row", alignItems: "center", gap: 3 }, iconCircle: { width: 32, height: 32, borderRadius: 11, alignItems: "center", justifyContent: "center" }, pill: { borderRadius: design.radius.sm, paddingHorizontal: 8, paddingVertical: 5, alignSelf: "flex-start" }, track: { height: 7, borderRadius: 5, marginTop: 7, overflow: "hidden" }, fill: { height: "100%", borderRadius: 5 }, metric: { minHeight: 123, shadowColor: design.shadow.color, shadowOpacity: 0.16, shadowRadius: 14, shadowOffset: { width: 0, height: 7 } }, dotNumber: { flexDirection: "row", alignItems: "center", gap: 4, minHeight: 28 }, dotGlyph: { gap: 2 }, dotRow: { flexDirection: "row", gap: 2 }, dot: { width: 3, height: 3, borderRadius: 2 } });
