import { ReactNode } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";

import { design } from "@/constants/design";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { accentTone, densityTokens, useAppearance } from "@/lib/appearance";

const DOTS: Record<string, string[]> = { "0": ["111", "101", "101", "101", "111"], "1": ["010", "110", "010", "010", "111"], "2": ["110", "001", "010", "100", "111"], "3": ["110", "001", "010", "001", "110"], "4": ["101", "101", "111", "001", "001"], "5": ["111", "100", "110", "001", "110"], "6": ["011", "100", "111", "101", "111"], "7": ["111", "001", "010", "010", "010"], "8": ["111", "101", "111", "101", "111"], "9": ["111", "101", "111", "001", "110"], ".": ["0", "0", "0", "0", "1"], "%": ["1001", "0010", "0100", "1001", "0010"], "—": ["111", "000", "000", "000", "111"] };

export const ui = StyleSheet.create({
  screen: { paddingHorizontal: design.spacing.lg, paddingTop: design.spacing.lg, paddingBottom: design.spacing.xxl },
  row: { flexDirection: "row", alignItems: "center" },
  between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  eyebrow: { fontSize: design.typography.eyebrow, letterSpacing: design.typography.tracking, textTransform: "uppercase", fontWeight: "800" },
  title: { fontSize: design.typography.display, lineHeight: 36, fontWeight: "800", letterSpacing: -0.8 },
  subtitle: { fontSize: design.typography.body, lineHeight: 20 },
  card: { borderRadius: design.radius.lg, padding: design.spacing.lg, borderWidth: 1, shadowColor: design.shadow.color, shadowOpacity: design.shadow.opacity, shadowRadius: design.shadow.radius, shadowOffset: { width: 0, height: design.shadow.y } },
  sectionTitle: { fontSize: 16, fontWeight: "800", letterSpacing: -0.2 },
  small: { fontSize: design.typography.caption, lineHeight: 15 },
});

export function DotNumber({ value, color = design.colors.ink, size = 3 }: { value: string; color?: string; size?: number }) { return <View style={styles.dotNumber}>{value.split("").map((char, charIndex) => <View key={`${char}-${charIndex}`} style={styles.dotGlyph}>{(DOTS[char] ?? DOTS["—"]).map((row, rowIndex) => <View key={rowIndex} style={styles.dotRow}>{row.split("").map((bit, bitIndex) => <View key={bitIndex} style={[styles.dot, { width: size, height: size, borderRadius: size, backgroundColor: bit === "1" ? color : "transparent" }]} />)}</View>)}</View>)}</View>; }

export function SectionHeader({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { const colors = useColors(); const { accentIntensity, density } = useAppearance(); const accent = accentTone(colors.primary, accentIntensity); const spacing = densityTokens[density]; return <View style={[ui.between, { marginTop: 26, marginBottom: spacing.sectionGap }]}><Text style={[ui.sectionTitle, { color: colors.foreground }]}>{title}</Text>{action && (onAction ? <Pressable onPress={onAction} style={({ pressed }) => [styles.action, pressed && { opacity: 0.55 }]}><Text style={{ color: accent, fontSize: 12, fontWeight: "800" }}>{action}</Text><IconSymbol name="chevron.right" size={16} color={accent} /></Pressable> : <Text style={{ color: accent, fontSize: 12, fontWeight: "800" }}>{action}</Text>)}</View>; }

export function GlassCard({ children, style, onPress }: { children: ReactNode; style?: object; onPress?: () => void }) { const colors = useColors(); const content = <View style={[ui.card, { backgroundColor: `${colors.surface}E8`, borderColor: `${colors.border}CC` }, style]}>{children}</View>; return onPress ? <Pressable onPress={onPress} style={({ pressed }) => [pressed && { opacity: 0.72, transform: [{ scale: 0.99 }] }]}>{content}</Pressable> : content; }

export function MetricCard({ label, value, detail, icon, accent = "primary", onPress }: { label: string; value: string; detail?: string; icon: string; accent?: "primary" | "success" | "warning"; onPress?: () => void }) { const colors = useColors(); const { density } = useAppearance(); const spacing = densityTokens[density]; const map: Record<string, { gradient: [string, string]; fg: string; accent: string }> = { "Walk-ins": { gradient: ["#4E7CF0", "#65B8F2"], fg: "#FFFFFF", accent: "#DDEBFF" }, Sales: { gradient: ["#7656D8", "#B07EEB"], fg: "#FFFFFF", accent: "#F2E9FF" }, Conversion: { gradient: ["#159FC7", "#56D1D7"], fg: "#FFFFFF", accent: "#E4FFFF" }, Lost: { gradient: ["#D95791", "#F18CB7"], fg: "#FFFFFF", accent: "#FFE7F1" }, "Follow-ups": { gradient: ["#2DAA7B", "#6ED5A9"], fg: "#FFFFFF", accent: "#E2FFF1" } }; const tile = map[label] ?? { gradient: [colors.primary, design.colors.cyan] as [string, string], fg: "#FFFFFF", accent: "#FFFFFF" }; const content = <LinearGradient colors={tile.gradient} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={[ui.card, styles.metric, { padding: spacing.cardPadding, borderColor: `${tile.accent}88` }]}><View style={[ui.between, { marginBottom: 10 }]}><Text style={[ui.eyebrow, { color: `${tile.fg}CC` }]}>{label}</Text><View style={[styles.iconCircle, { backgroundColor: `${tile.fg}22` }]}><IconSymbol name={icon} size={17} color={tile.fg} /></View></View><DotNumber value={value} color={tile.fg} size={3} /><Text style={[ui.small, { color: `${tile.fg}CC`, marginTop: 7 }]}>{detail}</Text></LinearGradient>; return onPress ? <Pressable onPress={onPress} style={({ pressed }) => [pressed && { opacity: 0.72 }]}>{content}</Pressable> : content; }

export function Pill({ children, color, background }: { children: ReactNode; color?: string; background?: string }) { const colors = useColors(); const { accentIntensity, density } = useAppearance(); const accent = accentTone(color ?? colors.primary, accentIntensity); const spacing = densityTokens[density]; return <View style={[styles.pill, { paddingVertical: Math.max(4, spacing.controlPadding - 4), backgroundColor: background ?? `${accent}18` }]}><Text style={{ color: accent, fontSize: 11, fontWeight: "800" }}>{children}</Text></View>; }

export function BarList({ rows, max, color }: { rows: { label: string; value: number; meta?: string }[]; max?: number; color?: string }) { const colors = useColors(); const { accentIntensity, density } = useAppearance(); const maxValue = max ?? Math.max(...rows.map((row) => row.value), 1); const accent = accentTone(color ?? colors.primary, accentIntensity); return <View style={{ gap: densityTokens[density].chartGap }}>{rows.map((row) => <View key={row.label}><View style={ui.between}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "700", flex: 1 }}>{row.label}</Text><Text style={{ color: colors.muted, fontSize: 11, fontWeight: "700" }}>{row.meta ?? row.value}</Text></View><View style={[styles.track, { backgroundColor: colors.background }]}><View style={[styles.fill, { width: `${Math.max(4, row.value / maxValue * 100)}%`, backgroundColor: accent }]} /></View></View>)}</View>; }

export function EmptyState({ title, description }: { title: string; description: string }) { const colors = useColors(); return <GlassCard style={{ alignItems: "center", paddingVertical: 28 }}><IconSymbol name="chart.bar.fill" size={28} color={colors.muted} /><Text style={{ color: colors.foreground, fontWeight: "800", marginTop: 10 }}>{title}</Text><Text style={{ color: colors.muted, textAlign: "center", fontSize: 12, lineHeight: 18, marginTop: 5 }}>{description}</Text></GlassCard>; }

const styles = StyleSheet.create({ action: { flexDirection: "row", alignItems: "center", gap: 3 }, iconCircle: { width: 32, height: 32, borderRadius: 11, alignItems: "center", justifyContent: "center" }, pill: { borderRadius: design.radius.sm, paddingHorizontal: 8, paddingVertical: 5, alignSelf: "flex-start" }, track: { height: 7, borderRadius: 5, marginTop: 7, overflow: "hidden" }, fill: { height: "100%", borderRadius: 5 }, metric: { minHeight: 123, shadowColor: design.shadow.color, shadowOpacity: 0.16, shadowRadius: 14, shadowOffset: { width: 0, height: 7 } }, dotNumber: { flexDirection: "row", alignItems: "center", gap: 4, minHeight: 28 }, dotGlyph: { gap: 2 }, dotRow: { flexDirection: "row", gap: 2 }, dot: { width: 3, height: 3, borderRadius: 2 } });
