import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { BarList, MetricCard, Pill, SectionHeader, ui } from "@/components/ui-kit";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { CATEGORIES, DateRange, inRange, rangeLabel, useApp } from "@/lib/app-store";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function DashboardScreen() {
  const colors = useColors();
  const { walkIns, staff, isDemo } = useApp();
  const [range, setRange] = useState<DateRange>("month");
  const rows = useMemo(() => walkIns.filter((row) => inRange(row.date, range)), [walkIns, range]);
  const sales = rows.filter((row) => row.sold);
  const lost = rows.filter((row) => !row.sold);
  const conversion = rows.length ? Math.round((sales.length / rows.length) * 100) : 0;
  const followUps = rows.filter((row) => row.followUpRequired).length;
  const staffStats = staff.map((person) => { const own = rows.filter((row) => row.staffId === person.id); const ownSales = own.filter((row) => row.sold).length; return { person, walkIns: own.length, sales: ownSales, conversion: own.length ? Math.round(ownSales / own.length * 100) : 0 }; }).filter((item) => item.walkIns > 0).sort((a, b) => b.conversion - a.conversion);
  const categoryStats = CATEGORIES.map((category) => { const own = rows.filter((row) => row.category === category); const ownSales = own.filter((row) => row.sold).length; return { category, walkIns: own.length, sales: ownSales, conversion: own.length ? Math.round(ownSales / own.length * 100) : 0 }; }).filter((item) => item.walkIns > 0).sort((a, b) => b.walkIns - a.walkIns);
  const reasons = Object.entries(lost.reduce<Record<string, number>>((acc, row) => { const reason = row.lostReason ?? "Not specified"; acc[reason] = (acc[reason] ?? 0) + 1; return acc; }, {})).map(([label, value]) => ({ label, value, meta: `${Math.round(value / Math.max(lost.length, 1) * 100)}%` })).sort((a, b) => b.value - a.value).slice(0, 5);
  const byHour = Object.entries(rows.reduce<Record<string, number>>((acc, row) => { const hour = `${Number(row.time.split(":")[0])}:00`; acc[hour] = (acc[hour] ?? 0) + 1; return acc; }, {})).map(([label, value]) => ({ label, value })).sort((a, b) => Number(a.label) - Number(b.label));
  const bestStaff = staffStats[0];
  return <ScreenContainer containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={ui.between}><View><Text style={[ui.eyebrow, { color: colors.primary }]}>PERFORMANCE INTELLIGENCE</Text><Text style={[ui.title, { color: colors.foreground, marginTop: 5 }]}>Dashboard</Text><Text style={[ui.subtitle, { color: colors.muted, marginTop: 4 }]}>{rangeLabel(range)} · actual recorded data</Text></View><View style={[styles.live, { backgroundColor: `${colors.success}16` }]}><View style={[styles.liveDot, { backgroundColor: colors.success }]} /><Text style={{ color: colors.success, fontSize: 10, fontWeight: "900" }}>LIVE</Text></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.ranges}>{(["today", "yesterday", "week", "month"] as DateRange[]).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.range, { backgroundColor: range === item ? colors.foreground : colors.surface, borderColor: range === item ? colors.foreground : colors.border }]}><Text style={{ color: range === item ? colors.background : colors.foreground, fontSize: 11, fontWeight: "800" }}>{rangeLabel(item)}</Text></Pressable>)}</ScrollView>
    {isDemo && <View style={[styles.demoTag, { backgroundColor: `${colors.primary}10`, borderColor: `${colors.primary}26` }]}><IconSymbol name="chart.bar.fill" size={15} color={colors.primary} /><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>DEMO DATA PREVIEW · Replace with live shop activity</Text></View>}
    <View style={styles.metricGrid}><MetricCard label="Total walk-ins" value={String(rows.length)} detail={`${rangeLabel(range)} window`} icon="person.2.fill" /><MetricCard label="Total sales" value={String(sales.length)} detail={`${conversion}% conversion`} icon="checkmark.circle.fill" accent="success" /><MetricCard label="Lost customers" value={String(lost.length)} detail={`${rows.length ? Math.round(lost.length / rows.length * 100) : 0}% lost rate`} icon="arrow.down.right" accent="warning" /><MetricCard label="Follow-ups" value={String(followUps)} detail="Created in range" icon="calendar.badge.clock" accent="primary" /></View>
    <SectionHeader title="Sales funnel" /><View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.funnelRow}><FunnelStep label="Walk-ins" value={rows.length} color={colors.primary} /><IconSymbol name="chevron.right" size={18} color={colors.muted} /><FunnelStep label="Serious" value={rows.filter((row) => row.intent !== "Browsing").length} color="#6B7DF3" /><IconSymbol name="chevron.right" size={18} color={colors.muted} /><FunnelStep label="Sales" value={sales.length} color={colors.success} /></View><View style={[styles.formula, { backgroundColor: colors.background }]}><IconSymbol name="target" size={16} color={colors.primary} /><Text style={{ color: colors.muted, fontSize: 11 }}>Conversion = sales ÷ walk-ins × 100 · {conversion}% for {rangeLabel(range).toLowerCase()}</Text></View></View>
    <SectionHeader title="Category performance" action="All categories" /><View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{categoryStats.length ? categoryStats.map((item) => <View key={item.category} style={[styles.categoryRow, { borderBottomColor: colors.border }]}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "800", flex: 1 }}>{item.category}</Text><Text style={{ color: colors.muted, fontSize: 11, width: 52 }}>{item.walkIns} in</Text><Text style={{ color: colors.success, fontSize: 11, fontWeight: "800", width: 52 }}>{item.sales} sold</Text><Pill color={item.conversion >= conversion ? colors.success : colors.warning} background={item.conversion >= conversion ? `${colors.success}16` : `${colors.warning}16`}>{item.conversion}%</Pill></View>) : <Text style={{ color: colors.muted, fontSize: 12 }}>Not enough data yet.</Text>}</View>
    <SectionHeader title="Staff performance" action="Raw + conversion" /><View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{staffStats.length ? staffStats.map((item, index) => <View key={item.person.id} style={[styles.staffRow, { borderBottomColor: colors.border }]}><View style={[styles.rank, { backgroundColor: index === 0 ? `${colors.warning}18` : colors.background }]}><Text style={{ color: index === 0 ? colors.warning : colors.muted, fontWeight: "900", fontSize: 11 }}>{String(index + 1).padStart(2, "0")}</Text></View><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 13, fontWeight: "900" }}>{item.person.name}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 3 }}>{item.walkIns} walk-ins · {item.sales} sales</Text></View><View style={{ alignItems: "flex-end" }}><Text style={{ color: item.conversion >= conversion ? colors.success : colors.warning, fontSize: 17, fontWeight: "900" }}>{item.conversion}%</Text><Text style={{ color: colors.muted, fontSize: 10 }}>conversion</Text></View></View>) : <Text style={{ color: colors.muted, fontSize: 12 }}>Not enough data yet.</Text>}{staffStats.some((item) => item.walkIns < 5) && <Text style={{ color: colors.warning, fontSize: 10, marginTop: 11 }}>Small sample warning: conversion rankings are directional when a staff member has handled fewer than 5 walk-ins.</Text>}</View>
    <SectionHeader title="Why we lose sales" action="Lost analysis" /><View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{reasons.length ? <BarList rows={reasons} color={colors.warning} /> : <Text style={{ color: colors.muted, fontSize: 12 }}>No lost-sale reasons recorded in this range.</Text>}</View>
    <SectionHeader title="Traffic by time" /><View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{byHour.length ? <BarList rows={byHour} color="#6B7DF3" /> : <Text style={{ color: colors.muted, fontSize: 12 }}>Not enough data yet.</Text>}{bestStaff && <View style={[styles.opportunity, { backgroundColor: `${colors.primary}10` }]}><IconSymbol name="flame.fill" size={16} color={colors.primary} /><Text style={{ color: colors.foreground, fontSize: 11, lineHeight: 17, flex: 1 }}>Data signal: <Text style={{ fontWeight: "900" }}>{bestStaff.person.name}</Text> currently leads conversion at {bestStaff.conversion}% across {bestStaff.walkIns} walk-ins. Interpretation is directional, not a judgment.</Text></View>}</View>
    <View style={[styles.note, { borderColor: colors.border }]}><Text style={{ color: colors.muted, fontSize: 10, lineHeight: 15 }}>Metrics are calculated from recorded customer interactions. Customers, enquiries, sales and bikes sold are kept distinct in the data model.</Text></View>
  </ScrollView></ScreenContainer>;
}
function FunnelStep({ label, value, color }: { label: string; value: number; color: string }) { return <View style={{ alignItems: "center", flex: 1 }}><Text style={{ color, fontSize: 24, fontWeight: "900" }}>{value}</Text><Text style={{ color: "#718096", fontSize: 10, fontWeight: "800", marginTop: 3 }}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 32 }, live: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8 }, liveDot: { width: 6, height: 6, borderRadius: 3 }, ranges: { gap: 7, paddingVertical: 17 }, range: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 11, paddingVertical: 8 }, demoTag: { borderWidth: 1, borderRadius: 10, padding: 10, flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 12 }, metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, funnelRow: { flexDirection: "row", alignItems: "center", gap: 4 }, formula: { flexDirection: "row", alignItems: "center", gap: 7, padding: 10, borderRadius: 10, marginTop: 17 }, categoryRow: { flexDirection: "row", alignItems: "center", paddingVertical: 11, borderBottomWidth: 1 }, staffRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 12, borderBottomWidth: 1 }, rank: { width: 29, height: 29, borderRadius: 10, alignItems: "center", justifyContent: "center" }, opportunity: { flexDirection: "row", gap: 8, padding: 10, borderRadius: 11, marginTop: 16 }, note: { borderWidth: 1, borderRadius: 12, padding: 11, marginTop: 24 },
});
