import { useState } from "react";
import { useRouter } from "expo-router";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from "react-native";

import { Pill, SectionHeader, ui } from "@/components/ui-kit";
import { StaffAvatar } from "@/components/staff-avatar";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { toCsv, useApp } from "@/lib/app-store";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { appearanceLabels, useAppearance, type AccentIntensity, type AppearanceMode, type UiDensity } from "@/lib/appearance";

export default function MoreScreen() {
  const colors = useColors();
  const router = useRouter();
  const appearance = useAppearance();
  const { staff, bikes, walkIns, addStaff, addBike, importCsv, clearDemoData, resetDemoData, isDemo } = useApp();
  const [showStaff, setShowStaff] = useState(false);
  const [showBikes, setShowBikes] = useState(false);
  const [showImport, setShowImport] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [newStaff, setNewStaff] = useState("");
  const [newBike, setNewBike] = useState("");
  const [csv, setCsv] = useState("DATE,TIME,ATTENDED,ENQUIRY,SOLD?,BIKE NAME\n2026-09-14,10:30,Rinshid,Road,No,\n");
  const exportData = async () => { const value = toCsv(walkIns, staff, bikes); try { await Share.share({ message: value, title: "CycleIntel walk-in export.csv" }); } catch { Alert.alert("Export ready", "Your CSV export was prepared from the current filtered dataset."); } };
  return <ScreenContainer containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={[ui.eyebrow, { color: colors.primary }]}>CONTROL CENTRE</Text><Text style={[ui.title, { color: colors.foreground, marginTop: 5 }]}>More</Text><Text style={[ui.subtitle, { color: colors.muted, marginTop: 4 }]}>Manage the building blocks behind your sales signal.</Text>
    <View style={[styles.profile, { backgroundColor: `${colors.surface}F2`, borderColor: `${colors.primary}28` }]}><View style={[styles.profileIcon, { backgroundColor: `${colors.primary}12`, borderColor: `${colors.primary}24` }]}><Text style={{ color: colors.primary, fontWeight: "900", fontSize: 16 }}>CI</Text></View><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 15, fontWeight: "900" }}>CycleIntel workspace</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 4 }}>Admin · Local-first workspace</Text></View><Pill color={colors.primary} background={`${colors.primary}14`}>v1.0</Pill></View>
    <SectionHeader title="Manage" />
    <View style={styles.menuGrid}><MenuCard icon="person.badge.plus" title="Staff" detail={`${staff.filter((item) => item.active).length} active`} onPress={() => setShowStaff(!showStaff)} /><MenuCard icon="shippingbox" title="Bikes" detail={`${bikes.filter((item) => item.status === "Available").length} available`} onPress={() => setShowBikes(!showBikes)} /><MenuCard icon="doc.text.fill" title="Reports" detail="Performance analysis" onPress={() => router.push("/analysis" as never)} /><MenuCard icon="gearshape.fill" title="Settings" detail="Appearance & workspace" onPress={() => setShowSettings(!showSettings)} /></View>
    {showSettings && <AppearancePanel colors={colors} mode={appearance.mode} accentIntensity={appearance.accentIntensity} density={appearance.density} setMode={appearance.setMode} setAccentIntensity={appearance.setAccentIntensity} setDensity={appearance.setDensity} reset={appearance.resetAppearance} />}
    {showStaff && <View style={[ui.card, styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "900", fontSize: 14 }}>Staff directory</Text>{staff.map((person) => <View key={person.id} style={[ui.between, styles.listRow, { borderBottomColor: colors.border }]}><View style={ui.row}><StaffAvatar staff={person} size={34} /><View style={{ marginLeft: 9 }}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "800" }}>{person.name}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 2 }}>{person.jobTitle ?? person.role}</Text></View></View><Pill color={colors.success} background={`${colors.success}16`}>{person.active ? "ACTIVE" : "OFF"}</Pill></View>)}<View style={styles.inlineForm}><TextInput value={newStaff} onChangeText={setNewStaff} placeholder="Add employee" placeholderTextColor={colors.muted} style={[styles.formInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /><Pressable onPress={() => { if (newStaff.trim()) { addStaff(newStaff.trim()); setNewStaff(""); } }} style={[styles.formButton, { backgroundColor: colors.primary }]}><IconSymbol name="plus.circle.fill" size={17} color="#FFFFFF" /></Pressable></View></View>}
    {showBikes && <View style={[ui.card, styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "900", fontSize: 14 }}>Bike inventory</Text>{bikes.slice(0, 6).map((bike) => <View key={bike.id} style={[ui.between, styles.listRow, { borderBottomColor: colors.border }]}><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "800" }}>{bike.brand} {bike.model}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 2 }}>{bike.type} · {bike.size} · £{bike.price.toLocaleString()}</Text></View><Pill color={bike.status === "Available" ? colors.success : colors.muted} background={bike.status === "Available" ? `${colors.success}16` : colors.background}>{bike.status.toUpperCase()}</Pill></View>)}<View style={styles.inlineForm}><TextInput value={newBike} onChangeText={setNewBike} placeholder="Brand + model" placeholderTextColor={colors.muted} style={[styles.formInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /><Pressable onPress={() => { if (newBike.trim()) { addBike({ brand: "New", model: newBike.trim(), type: "Other", size: "—", price: 0, status: "Available", sku: `NEW-${Date.now()}` }); setNewBike(""); } }} style={[styles.formButton, { backgroundColor: colors.primary }]}><IconSymbol name="plus.circle.fill" size={17} color="#FFFFFF" /></Pressable></View></View>}
    <SectionHeader title="Data tools" />
    <View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><ToolRow icon="upload" title="Import historical data" detail="CSV preview + duplicate detection" onPress={() => setShowImport(!showImport)} /><ToolRow icon="arrow.down.doc" title="Export walk-ins" detail="Share CSV of all recorded interactions" onPress={exportData} /><ToolRow icon="chart.pie.fill" title="KPI formulas" detail="Sales ÷ walk-ins × 100" onPress={() => Alert.alert("KPI definitions", "Conversion rate = sales ÷ walk-ins × 100\nLost rate = lost walk-ins ÷ total walk-ins × 100\nCategory conversion = category sales ÷ category walk-ins × 100") } /></View>
    {showImport && <View style={[ui.card, styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "900", fontSize: 14 }}>Import preview</Text><Text style={{ color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 5 }}>Paste CSV exported from Google Sheets. Existing records are preserved and obvious duplicates are skipped.</Text><TextInput multiline value={csv} onChangeText={setCsv} style={[styles.csv, { color: colors.foreground, backgroundColor: colors.background, borderColor: colors.border }]} placeholderTextColor={colors.muted} /><Pressable onPress={() => { const result = importCsv(csv); Alert.alert("Import complete", `${result.imported} imported · ${result.skipped} duplicate rows skipped.`); setShowImport(false); }} style={[styles.importButton, { backgroundColor: colors.primary }]}><IconSymbol name="upload" size={17} color="#FFFFFF" /><Text style={{ color: "#FFFFFF", fontSize: 12, fontWeight: "900" }}>Preview & import</Text></Pressable></View>}
    <SectionHeader title="Demo workspace" />
    <View style={[ui.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={ui.between}><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 13, fontWeight: "900" }}>{isDemo ? "Demo data is active" : "Live data workspace"}</Text><Text style={{ color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }}>{isDemo ? "Explore the analytics, then clear the seeded records before production use." : "Your new interactions are stored locally on this device."}</Text></View><IconSymbol name="arrow.clockwise" size={18} color={colors.muted} /></View><View style={styles.demoActions}><Pressable onPress={() => { clearDemoData(); Alert.alert("Demo data cleared", "Seeded demo records have been removed."); }} style={[styles.secondaryButton, { borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontSize: 11, fontWeight: "800" }}>Clear demo</Text></Pressable><Pressable onPress={() => { resetDemoData(); Alert.alert("Demo reset", "The sample workspace is ready again."); }} style={[styles.secondaryButton, { borderColor: colors.border }]}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "800" }}>Reset demo</Text></Pressable></View></View>
    <Text style={{ color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 22 }}>V1 is local-first by design so the shop can work independently. The relational data model and API-ready entities are prepared for Google Sheets, Shopify, WhatsApp, CRM, and cloud sync integrations later.</Text>
  </ScrollView></ScreenContainer>;
}
function MenuCard({ icon, title, detail, onPress }: { icon: string; title: string; detail: string; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.menuCard, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.7 }]}><View style={[styles.menuIcon, { backgroundColor: `${colors.primary}14` }]}><IconSymbol name={icon} size={19} color={colors.primary} /></View><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "900", marginTop: 9 }}>{title}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 3 }}>{detail}</Text></Pressable>; }
function ToolRow({ icon, title, detail, onPress }: { icon: string; title: string; detail: string; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.tool, pressed && { opacity: 0.65 }]}><View style={[styles.toolIcon, { backgroundColor: `${colors.primary}14` }]}><IconSymbol name={icon} size={17} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "900" }}>{title}</Text><Text style={{ color: colors.muted, fontSize: 10, marginTop: 3 }}>{detail}</Text></View><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>; }
function AppearancePanel({ colors, mode, accentIntensity, density, setMode, setAccentIntensity, setDensity, reset }: { colors: ReturnType<typeof useColors>; mode: AppearanceMode; accentIntensity: AccentIntensity; density: UiDensity; setMode: (value: AppearanceMode) => void; setAccentIntensity: (value: AccentIntensity) => void; setDensity: (value: UiDensity) => void; reset: () => void }) { return <View style={[ui.card, styles.appearancePanel, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={ui.between}><View><Text style={{ color: colors.foreground, fontSize: 14, fontWeight: "900" }}>Appearance</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 4 }}>Tune the visual energy and information density.</Text></View><Pressable onPress={reset}><Text style={{ color: colors.primary, fontSize: 11, fontWeight: "900" }}>Reset</Text></Pressable></View><SettingGroup label="Theme mode" description="Choose a bright, low-light, or system-following interface." options={["light", "dim", "automatic"]} value={mode} onChange={setMode} colors={colors} labels={appearanceLabels.mode} /><SettingGroup label="Accent intensity" description="Controls colour strength in highlights, pills, and charts." options={["soft", "balanced", "vivid"]} value={accentIntensity} onChange={setAccentIntensity} colors={colors} labels={appearanceLabels.accentIntensity} /><SettingGroup label="UI density" description="Choose how much breathing room each surface uses." options={["compact", "comfortable", "airy"]} value={density} onChange={setDensity} colors={colors} labels={appearanceLabels.density} /></View>; }
function SettingGroup<T extends string>({ label, description, options, value, onChange, colors, labels }: { label: string; description: string; options: T[]; value: T; onChange: (value: T) => void; colors: ReturnType<typeof useColors>; labels: Record<string, string> }) { return <View style={styles.settingGroup}><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "900" }}>{label}</Text><Text style={{ color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3 }}>{description}</Text><View style={styles.settingOptions}>{options.map((option) => <Pressable key={option} onPress={() => onChange(option)} style={[styles.settingOption, { backgroundColor: value === option ? `${colors.primary}18` : colors.background, borderColor: value === option ? colors.primary : colors.border }]}><Text style={{ color: value === option ? colors.primary : colors.muted, fontSize: 10, fontWeight: "900" }}>{labels[option] ?? option}</Text></Pressable>)}</View></View>; }
  const styles = StyleSheet.create({ content: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 32, maxWidth: 1180, width: "100%", alignSelf: "center" }, profile: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 20, borderWidth: 1, padding: 14, marginTop: 22, shadowColor: "#9AAAC0", shadowOpacity: 0.1, shadowRadius: 18, shadowOffset: { width: 0, height: 7 } }, profileIcon: { width: 38, height: 38, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center" }, menuGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, menuCard: { width: "48.5%", minHeight: 111, borderRadius: 15, borderWidth: 1, padding: 13 }, menuIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center" }, panel: { marginTop: 12 }, appearancePanel: { marginTop: 12 }, settingGroup: { marginTop: 19 }, settingOptions: { flexDirection: "row", gap: 7, marginTop: 9 }, settingOption: { flex: 1, borderWidth: 1, borderRadius: 10, paddingVertical: 10, alignItems: "center", justifyContent: "center" }, listRow: { paddingVertical: 10, borderBottomWidth: 1 }, inlineForm: { flexDirection: "row", gap: 8, marginTop: 13 }, formInput: { flex: 1, minHeight: 40, borderWidth: 1, borderRadius: 10, paddingHorizontal: 11, fontSize: 12 }, formButton: { width: 42, minHeight: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" }, tool: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#E5EAF0" }, toolIcon: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" }, csv: { minHeight: 105, marginTop: 12, borderWidth: 1, borderRadius: 10, padding: 10, fontSize: 11, textAlignVertical: "top" }, importButton: { minHeight: 42, borderRadius: 11, marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, demoActions: { flexDirection: "row", gap: 8, marginTop: 14 }, secondaryButton: { flex: 1, borderWidth: 1, borderRadius: 10, minHeight: 35, alignItems: "center", justifyContent: "center" },
});
